# Use root/example as user/password credentials
version: '3.1'
services:
  cache:
    image: redislabs/redismod:latest
    restart: always
    ports:
      - "6379:6379"
  db:
    image: mariadb
    restart: always
    ports:
      - "3306:3306"
    environment:
      MYSQL_ROOT_PASSWORD: example
    volumes:
      - db-data:/var/lib/mysql
  postgres:
    image: postgres
    restart: always
    environment:
      POSTGRES_PASSWORD: example
    ports:
      - "5432:5432"
#  express:
#    build:
#      context: .
#      dockerfile: docker/Dockerfile.dev
#    restart: always
#    depends_on:
#      - db
#    ports:
#      - 5000:5000
#    links:
#      - db:db
#    volumes:
#      - express-node_modules:/app/node_modules
#      - ./:/app
#    env_file:
#      - .env

volumes:
  db-data: