FROM node:16-buster as builder

WORKDIR /app
COPY . .
RUN yarn install --frozen-lockfile

RUN yarn prisma generate
RUN yarn build

FROM node:16-alpine

WORKDIR /app
COPY --from=builder /app/package.json ./package.json
COPY --from=builder /app/yarn.lock ./yarn.lock
COPY --from=builder /app/build ./

RUN yarn install --prod --frozen-lockfile

CMD ["yarn", "start"]
